DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "notes" CASCADE;
DROP TABLE IF EXISTS "noterefs" CASCADE;
DROP TABLE IF EXISTS "contacts" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "tokens" CASCADE;
DROP TABLE IF EXISTS "stripe_tokens" CASCADE;

DROP TYPE noteref_status;
DROP TYPE noteref_role;
DROP TYPE id_status;
DROP TYPE token_kind;
